/**
 * config.js
 * ゲームの設定ファイル。
 * ここを変更するだけで別テーマのゲームに変更可能。
 *
 * imagePath: null → emoji でプレースホルダー描画
 * imagePath: "images/xxx.png" → 実際の画像を使用
 */

const ICE_CREAMS = [
  {
    id: 1,
    name: "お花見だんご 〜さくら風味〜",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br01027_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 2,
    name: "マカロン マカロン",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00112_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 3,
    name: "バーガンディチェリー",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00001_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 4,
    name: "白桃ブランマンジェ",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00526_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 5,
    name: "さくら",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00126_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 6,
    name: "メルティ ストロベリー チョコレート",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00713_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 7,
    name: "ストロベリー ロイヤルミルクティー",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00509_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 8,
    name: "ラブラブポーション サーティワン",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00995_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 9,
    name: "ベリー ミーツ ピスタチオ",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00843_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 10,
    name: "サーティワン オールスターズ",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00134_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 11,
    name: "コットンキャンディ",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00071_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 12,
    name: "ストロベリー スペシャルタイム",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00343_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 13,
    name: "ラブポーション サーティワン",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00030_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 14,
    name: "バニラ",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00029_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 15,
    name: "ポッピングシャワー",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00058_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 16,
    name: "ジャモカコーヒー",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00002_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 17,
    name: "抹茶",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00023_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 18,
    name: "ストロベリーチーズケーキ",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00007_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 19,
    name: "チョコレート",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00025_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 20,
    name: "キャラメルリボン",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00013_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 21,
    name: "マスクメロン",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00020_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 22,
    name: "チョップドチョコレート",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00008_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 23,
    name: "ラムレーズン",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00028_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 24,
    name: "バナナアンドストロベリー",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00012_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 25,
    name: "ジャモカ アーモンドファッジ",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00005_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 26,
    name: "チョコレートミント",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00004_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 27,
    name: "ナッツトゥユー",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00011_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 28,
    name: "大納言あずき",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00033_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 29,
    name: "クッキーアンドクリーム",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00019_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 30,
    name: "オレンジソルベ",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00041_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 31,
    name: "ベリーベリーストロベリー",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00027_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  },
  {
    id: 32,
    name: "ロッキーロード",
    emoji: "🍦",
    imagePath: "31ice_flavors/images/br00003_thumbnail_pc.png",
    bgColor: "#FFF8E7",
    borderColor: "#F5C842",
    textColor: "#8B6914",
  }
];

const GAME_CONFIG = {
  // ゲームの基本設定
  numColumns: 3,           // 同時に落下する列数
  baseFallSpeed: 0.9,      // 基本落下速度 (px/frame) - 序盤はゆっくり
  speedIncrement: 0.3,     // セットクリアごとの速度上昇
  maxFallSpeed: 5.0,       // 最大落下速度
  spawnIntervalMs: 2000,   // (未使用) アイスのスポーン間隔 (ms)

  // スコア
  hitScore: 150,           // 正しいアイスを撃った時の得点

  // Canvas サイズ（CSSでレスポンシブ対応）
  canvasWidth: 800,
  canvasHeight: 550,

  // アイスの描画サイズ
  iceWidth: 70,
  iceHeight: 85,

  // ビームの設定
  beamSpeed: 18,
  beamWidth: 6,
};
